---
version: "3.3"
services:
  ambition:
    container_name: ambition
    restart: always
    hostname: ambition
    ports:
      - 5000:5000
    build:
      context: .
      dockerfile: dockerFile.dev
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"