---
version: "3.3"
services:
  ambition:
    container_name: ambition
    restart: always
    hostname: ambition
    ports:
      - 8080:5000
    build:
      context: .
      dockerfile: dockerFile.dev
    volumes:
      - ./server:/usr/src/app/server
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    hostname: mongo
    ports:
      - "27017:27017"
